repoUrl: https://github.com/akolpakova/demo-argocd.git
targetRevision: testing-devex
## should I put defaults here as null ? like namespace ?

resourceKinds:
  apps:
    syncWave: 0
    enableAutoSync: true
    autoSyncPrune: false