environment: null
name: null

# clusterEnvironment: production

argocdInstanceType:
  production:
    syncWave: 0
    enableAutoSync: false
    autoSyncPrune: true
    argocdURL: http://localhost:8080

  development:
    syncWave: 0
    enableAutoSync: true
    autoSyncPrune: false
    argocdURL: http://localhost:8081

clusters:
  child-1-cucumber:
    environment: production
  child-2-potato:
    environment: development
