name: child-2-potato
argocdNamespace: argocd
argocdInstance: argocd-a
argocdURL: http://localhost:8080
environment: development


# name: child-2-potato
# argocdNamespace: namespace-b
# argocdInstance: argocd-b
# argocdURL: http://localhost:8081
# environment: development