apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-deploy
  namespace: namespace-b
spec:
  project: default
  source:
    repoURL: https://github.com/helm/examples.git
    targetRevision: main
    path: charts/hello-world
    helm:
      releaseName: test-deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: test-deploy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true