clusterName: test-deploy

defaults:
  app:
    destination:
      namespace: not-defined
  resource:
    destination:
      namespace: not-defined
  app-infra:
    destination:
      namespace: not-defined

resource-list:
  cluster-secrets:
    type: helm
    enabled: false
    project: default
    source:
      path: renderers/cluster-secrets
    helm:
      valueFiles:
        - "$values/clusters/clusters-list.yaml"
    destination:
      namespace: namespace-b