repoUrl: https://github.com/akolpakova/demo-argocd.git
targetRevision: test-team
namespace: argocd

resourceKinds:
  # apps:
  #   syncWave: 0
  #   enableAutoSync: true
  #   autoSyncPrune: false
  #   config: "app-config.yaml"

  resources:
    syncWave: 0
    autoSyncPrune: false
    enableAutoSync: true
    config: "resources-config.yaml"
